option(GEN_PDB "Generate PDB. Can cause some Anti-Cheat problems Default: OFF" OFF)
option(ENABLE_CRASHES "Enable crash options. Default: OFF" OFF)
option(ENABLE_SOCIALCLUB "Enable Social Club hooking. Default: ON" ON)
option(ENABLE_ASI_LOADER "Enable shitty built in ASI Loader. Default: ON" ON)
option(ENABLE_LUA "Enables YimMenu Lua api. Default: ON" ON)
