name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: windows-latest
    name: CI
    steps:
      - uses: actions/checkout@v3

      - name: Check CMake version
        run: cmake --version

      - name: Cache build/
        id: cache-build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Generate CMake project
        run: cmake -D CMAKE_BUILD_TYPE=Release -S. -Bbuild -G Ninja -DGEN_PDB=ON

      - name: Build 64bit release DLL
        run: cmake --build ./build --config Release --target YimMenu --

      - name: Check if DLL got built
        run: if (-Not (Test-Path -path "build/TupoyeMenu.dll")) {throw 1}

      - name: Rename DLL to TupoyeMenu-dev-{GITHUB_SHA}.dll
        run: |
          del TupoyeMenu-dev-*.dll
          ren TupoyeMenu.dll TupoyeMenu-dev-${{github.sha}}.dll
          del TupoyeMenu-dev-*.pdb
          ren TupoyeMenu.pdb TupoyeMenu-dev-${{github.sha}}.pdb
        working-directory: build/

      - name: Upload DLL
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: build/TupoyeMenu-dev-*.dll
      
      - name: Upload PDB
        uses: actions/upload-artifact@v3
        with:
          name: pdb
          path: build/TupoyeMenu-dev-*.pdb
